import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import Register from './auth/register';

const Home: NextPage = () => {
    return (
        <div>
        <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create Next App'/>
        </Head>
        <section>
        <Register />
        </section>
        </div>
    );
};

export default Home;