import { NextPage } from "next";
import Head from "next/head";
import React, {useEffect} from "react";
import Qr from "@/components/Qr/Qr";
import {useAppSelector} from "@/hooks/redux";
import {useRouter} from "next/router";



const Home: NextPage = () => {

    const router = useRouter()

    const {user} = useAppSelector(state => state.user)

    if(user === null){
        router.push('/auth')
    }


  return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create Next App" />
        </Head>

        <Qr/>
    </>
  );
};

export default Home;
